# Import

In [3]:
import pandas as pd

The project CSV files are stored in the data/raw

In [ ]:
ad_revenue = pd.read_csv('../data/raw/ad_revenue.csv')
iap_products = pd.read_csv('../data/raw/iap_products.csv')
matches = pd.read_csv('../data/raw/matches.csv')
purchases = pd.read_csv('../data/raw/purchases.csv')
sessions = pd.read_csv('../data/raw/sessions.csv')
ua_spend = pd.read_csv('../data/raw/ua_spend.csv')
users = pd.read_csv('../data/raw/users.csv')

Shapes

In [8]:
files = ['ad_revenue', 'iap_products','matches', 'purchases', 'sessions', 
        'ua_spend', 'users']

for f in files: 
    df = pd.read_csv(f'../data/raw/{f}.csv')
    print(f'{f}: {df.shape}')

ad_revenue: (19999, 6)
iap_products: (14, 5)
matches: (61716, 7)
purchases: (4558, 8)
sessions: (44945, 5)
ua_spend: (280, 6)
users: (8040, 6)

file: ad_revenue

In [ ]:
print(f'shape:{ad_revenue.shape}')
print(ad_revenue.dtypes)
print(ad_revenue.isnull().sum())
display(ad_revenue.head())

# Todo: Standardize categories
print(ad_revenue['tipo_ad'].value_counts())
print(ad_revenue['red_ad'].value_counts())
# revenue describe
print(ad_revenue['ingreso'].describe())

shape:(19999, 6)
id           int64
user_id      int64
fecha          str
tipo_ad        str
red_ad         str
ingreso    float64
dtype: object
id           0
user_id      0
fecha        0
tipo_ad      0
red_ad       0
ingreso    600
dtype: int64

         id  user_id       fecha       tipo_ad      red_ad  ingreso
0  40002095     2403  2024-07-06  Interstitial       admob   0.0797
1  40006648     2857  06/07/2024      rewarded       AdMob   0.0531
2  40010934     4805  2024-07-17      Rewarded       admob   0.0348
3  40015469     6446  03/07/2024      Rewarded       admob   0.0183
4  40016160     6679  2024-07-16  recompensado  ironsource   0.4685

tipo_ad
rewarded        4047
recompensado    3993
Rewarded        3925
interstitial    3094
Interstitial    2946
banner          1007
Banner           987
Name: count, dtype: int64
red_ad
admob         6121
AdMob         6031
ironsource    3957
ironSource    3890
Name: count, dtype: int64
count    19399.000000
mean         0.206093
std          0.178746
min          0.000200
25%          0.074650
50%          0.155900
75%          0.284550
max          1.872400
Name: ingreso, dtype: float64

file: iap_products

In [24]:
print(f'shape:{iap_products.shape}')
print(iap_products.dtypes)
print(iap_products.isnull().sum())
display(iap_products.head())

# Todo: Standardize categories
print(iap_products['tipo'].value_counts())

shape:(14, 5)
producto_id      int64
nombre             str
tipo               str
precio_base        str
monedas        float64
dtype: object
producto_id    0
nombre         0
tipo           0
precio_base    0
monedas        3
dtype: int64

   producto_id            nombre     tipo precio_base  monedas
0            1    Pack Monedas S  Monedas      0,99 €    100.0
1            2    Pack Monedas M  monedas      2,99 €    350.0
2            3    Pack Monedas L  monedas      4,99 €    650.0
3            4   Pack Monedas XL  monedas      9,99 €   1500.0
4            5  Pack Monedas XXL  monedas     19,99 €   3500.0

tipo
monedas            8
Monedas            3
suscripcion        2
quitar_anuncios    1
Name: count, dtype: int64

file: matches

In [29]:
print(f'shape: {matches.shape}')
print(matches.dtypes)
print(matches.isnull().sum())
display(matches.head())

# Todo: Standardize categories
print(matches['resultado'].value_counts())

# Describe
print(matches['movimientos'].describe())
print(matches['boosters_usados'].describe())

shape: (61716, 7)
partida_id           int64
user_id              int64
nivel                int64
fecha                  str
resultado              str
movimientos          int64
boosters_usados    float64
dtype: object
partida_id            0
user_id               0
nivel                 0
fecha                 0
resultado             0
movimientos           0
boosters_usados    1854
dtype: int64

,partida_id,user_id,nivel,fecha,resultado,movimientos,boosters_usados
0,20051872,7029,6,2024-07-11,fail,12,0.0
1,20028138,4696,3,2024-06-11,fail,24,0.0
2,20053463,7224,3,2024-07-04,win,12,1.0
3,20051328,6956,4,2024-07-04,ganada,14,2.0
4,20016282,3492,3,2024-07-07,win,32,0.0

resultado
win        11733
WIN        11728
ganada     11624
fail        8916
lose        8884
perdida     8831
Name: count, dtype: int64
count    61716.000000
mean        21.576334
std          7.906442
min         -3.000000
25%         16.000000
50%         22.000000
75%         27.000000
max         58.000000
Name: movimientos, dtype: float64
count    59862.000000
mean         0.563162
std          0.831332
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          3.000000
Name: boosters_usados, dtype: float64

file: purchases

In [33]:
print(f'shape: {purchases.shape}')
print(purchases.dtypes)
print(purchases.isnull().sum())
display(purchases.head())

# Todo: Standardize categories
print(purchases['moneda'].value_counts())
print(purchases['plataforma'].value_counts())

# Describe
print(purchases['reembolso'].describe())

shape: (4558, 8)
compra_id      int64
user_id        int64
producto_id    int64
fecha            str
importe          str
moneda           str
plataforma       str
reembolso      int64
dtype: object
compra_id      0
user_id        0
producto_id    0
fecha          0
importe        0
moneda         0
plataforma     0
reembolso      0
dtype: int64

,compra_id,user_id,producto_id,fecha,importe,moneda,plataforma,reembolso
0,30004059,7541,3,6 jun 2024,"4,99 €",eur,Android,0
1,30003960,6828,1,25/06/2024,"0,99 €",eur,ios,0
2,30000822,3481,1,2024-07-03,"0,99 €",eur,iOS,0
3,30003149,5905,10,2024-06-14,"1,99 €",EUR,Android,0
4,30002203,5013,12,2024-07-01,"2,49 €",EUR,android,0

moneda
EUR    3155
eur     921
€       470
MXN      12
Name: count, dtype: int64
plataforma
android    1067
ios         992
Android     964
iOS         901
AND         341
IOS         293
Name: count, dtype: int64
count    4558.000000
mean        0.014699
std         0.120360
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: reembolso, dtype: float64

file: sessions

In [45]:
print(f'shape: {sessions.shape}')
print(sessions.dtypes)
print(sessions.isnull().sum())
display(sessions.head())

# Todo: Standardize categories
print(sessions['plataforma'].value_counts())

# Describe
print(sessions['duracion_segundos'].describe())
atypical = sessions[sessions['duracion_segundos'].isin([-30,999999])]
print(f'atypical values: {atypical.shape}')

shape: (44945, 5)
evento_id            int64
user_id              int64
fecha                  str
duracion_segundos    int64
plataforma             str
dtype: object
evento_id            0
user_id              0
fecha                0
duracion_segundos    0
plataforma           0
dtype: int64

   evento_id  user_id        fecha  duracion_segundos plataforma
0   10020515     4475  14 jul 2024                263    Android
1   10017007     4009   2024-06-27                229        IOS
2   10003905     1363   2024-06-21                210        iOS
3   10042023     7630   11/07/2024                103        ios
4   10018908     4254   07/06/2024                332    Android

plataforma
android    10765
Android     9751
ios         9451
iOS         8287
AND         3627
IOS         3064
Name: count, dtype: int64
count     44945.000000
mean        583.905039
std       20005.028244
min         -30.000000
25%         104.000000
50%         180.000000
75%         255.000000
max      999999.000000
Name: duracion_segundos, dtype: float64
atypical values: (27, 5)

file: ua_spend

In [51]:
print(f'shape: {ua_spend.shape}')
print(ua_spend.dtypes)
print(ua_spend.isnull().sum())
display(ua_spend.head())

# Todo: Standardize categories
print(ua_spend['canal'].value_counts())

# Describe 
print(ua_spend[['instalaciones','impresiones', 'clics']].describe())

shape: (280, 6)
canal                str
fecha                str
gasto                str
instalaciones      int64
impresiones        int64
clics            float64
dtype: object
canal             0
fecha             0
gasto             0
instalaciones     0
impresiones       0
clics            11
dtype: int64

          canal       fecha    gasto  instalaciones  impresiones  clics
0  apple search  2024-06-22  11,53 €             11         1294   29.0
1      Facebook  12/07/2024  20,60 €             20         2307   67.0
2       organic  16/07/2024   0,00 €              2          249    5.0
3     coin_rush  2024-07-19  32,05 €             72         4997  146.0
4      coinrush  2024-07-02  58,45 €            129        15381  481.0

canal
meta            25
tiktok          24
organico        20
google          18
Meta            18
apple_search    16
TikTok          15
coinrush        14
orgánico        14
Google Ads      14
ASA             13
google_ads      12
tik_tok         11
Apple Search    11
apple search    10
organic         10
CoinRush         9
Organico         6
Google           6
coin_rush        4
facebook         4
Facebook         3
Coinrush         3
Name: count, dtype: int64
       instalaciones   impresiones       clics
count     280.000000    280.000000  269.000000
mean       28.571429   2895.246429   63.416357
std        33.868847   3439.726011   82.581560
min         0.000000    112.000000    2.000000
25%        10.000000    971.000000   19.000000
50%        19.500000   1816.500000   38.000000
75%        34.250000   3319.250000   77.000000
max       273.000000  23200.000000  766.000000

file: users

In [64]:
print(f'shape: {users.shape}')
print(users.dtypes)
print(users.isnull().sum())
display(users.head())
print(f'CLIENTES ÚNICOS: {users['user_id'].nunique()}')

# Todo: Standardize categories
print(users['canal_adquisicion'].value_counts())
print(users['pais'].value_counts())
print(users['plataforma'].value_counts())

# nulls values
null = users[users['version_app'].isnull()]
display(null)

shape: (8040, 6)
user_id              int64
fecha_instalacion      str
canal_adquisicion      str
pais                   str
plataforma             str
version_app            str
dtype: object
user_id                0
fecha_instalacion      0
canal_adquisicion      0
pais                   0
plataforma             0
version_app          297
dtype: int64

   user_id fecha_instalacion canal_adquisicion    pais plataforma version_app
0     1474        9 jul 2024          coinrush      es    Android       3.0.1
1     2148        12/07/2024          CoinRush      es    android         NaN
2     5036        2024-06-19            google  México        ios       2.9.5
3     1108        2024-07-03          coinrush      ES    Android       3.3.0
4     1931        2024-07-01          Coinrush  mexico        ios       3.1.0

CLIENTES ÚNICOS: 8000
canal_adquisicion
coinrush        1281
CoinRush         855
meta             636
google           578
Meta             409
coin_rush        407
Google Ads       399
facebook         397
tiktok           355
apple_search     311
google_ads       279
ASA              279
Coinrush         270
organico         266
TikTok           223
Apple Search     179
Facebook         168
orgánico         159
Google           151
apple search     137
organic          132
tik_tok          124
Organico          45
Name: count, dtype: int64
pais
ES          1864
MX          1268
España       834
PT           763
es           680
IT           568
México       554
mexico       459
Portugal     348
pt           292
Italia       244
it           166
Name: count, dtype: int64
plataforma
android    1995
Android    1747
ios        1641
iOS        1485
AND         629
IOS         543
Name: count, dtype: int64

,user_id,fecha_instalacion,canal_adquisicion,pais,plataforma,version_app
1,2148,12/07/2024,CoinRush,es,android,NaN
40,3231,2024-07-21,meta,es,ios,NaN
78,5357,21/07/2024,Google Ads,es,android,NaN
114,3929,2024-07-16,Meta,MX,Android,NaN
120,3096,2024-06-18,meta,ES,android,NaN
...,...,...,...,...,...,...
8002,4100,3 jul 2024,meta,IT,iOS,NaN
8010,4189,21/06/2024,meta,IT,android,NaN
8012,4716,08/07/2024,google_ads,México,ios,NaN
8028,2632,14/07/2024,coinrush,ES,Android,NaN
8035,2041,01/07/2024,coin_rush,MX,Android,NaN